"""add_is_exported_column_on_message

Revision ID: 20507ea70508
Revises: 2a1575f367ef
Create Date: 2025-02-27 17:03:54.955120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20507ea70508'
down_revision: Union[str, None] = '2a1575f367ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('is_exported', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_exported')
    # ### end Alembic commands ###
