"""initial_migration_sqlite

Revision ID: 2a1575f367ef
Revises: c3b7a2e9bfd5
Create Date: 2025-02-25 16:33:19.878450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1575f367ef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
        sa.Column('session_id', sa.String(), primary_key=True, index=True), # Bỏ length=255, index=True
        sa.Column('session_name', sa.String()), # Bỏ length=255
        sa.Column('ai_model', sa.String()), # Bỏ length=255
        sa.Column('ai_max_tokens', sa.Integer()),
        sa.Column('ai_response_time', sa.String()), # Bỏ length=255
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')) # DateTime không timezone
    )
    op.create_index('idx_sessions_session_id', 'sessions', ['session_id']) # Index cho SQLite
    op.create_table('messages',
        sa.Column('message_id', sa.String(), primary_key=True, index=True), # Bỏ length=255, index=True
        sa.Column('session_id', sa.String(), sa.ForeignKey('sessions.session_id'), nullable=False), # Bỏ length=255
        sa.Column('statement_index', sa.Integer(), index=True, nullable=False), # index=True
        sa.Column('sender', sa.String()), # Bỏ length=255
        sa.CheckConstraint("sender IN ('user', 'system')", name='sender_type_check'), # CheckConstraint giữ nguyên
        sa.Column('content', sa.Text()),
        sa.Column('timestamp', sa.DateTime()), # DateTime không timezone
        sa.Column('is_selected', sa.Boolean(), default=False), # default=False
        sa.Column('selected_at', sa.DateTime()) # DateTime không timezone
    )
    op.create_index('idx_messages_session_id', 'messages', ['session_id']) # Index cho SQLite
    op.create_index('idx_messages_statement_index', 'messages', ['statement_index']) # Index cho SQLite
    op.create_index('idx_messages_session_statement_index', 'messages', ['session_id', 'statement_index']) # Index cho SQLite
    op.create_table('summaries',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, index=True), # autoincrement=True cho SQLite Identity
        sa.Column('session_id', sa.String(), sa.ForeignKey('sessions.session_id'), nullable=False), # Bỏ length=255
        sa.Column('to_statement_index', sa.Integer(), nullable=False),
        sa.Column('summary_text', sa.Text())
    )
    op.create_index('idx_summaries_session_id', 'summaries', ['session_id']) # Index cho SQLite
    op.create_index('idx_summaries_to_statement_index', 'summaries', ['to_statement_index']) # Index cho SQLite
    op.create_index('idx_summaries_session_to_statement_index', 'summaries', ['session_id', 'to_statement_index']) # Index cho SQLite
# ### end Alembic commands ###
