"""add_selected_at_column_to_messages

Revision ID: 2f221e52c403
Revises: e5f5277a5ca4
Create Date: 2025-02-24 13:39:28.198017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f221e52c403'
down_revision: Union[str, None] = 'e5f5277a5ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True)) # Thêm cột selected_at
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'selected_at') # Xóa cột selected_at khi downgrade
    # ### end Alembic commands ###
