"""add fields to messages table

Revision ID: 8bec1fb6a11a
Revises: 718123c63d32
Create Date: 2025-03-05 10:10:12.976621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bec1fb6a11a'
down_revision: Union[str, None] = '718123c63d32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('images_path', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('files_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'files_path')
    op.drop_column('messages', 'images_path')
    # ### end Alembic commands ###
