"""Initial migration - Create tables (sessions, messages, summaries, users)

Revision ID: e5f5277a5ca4
Revises: 
Create Date: 2025-02-23 22:01:54.630685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f5277a5ca4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('session_id', sa.String(length=255), primary_key=True, nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=True),
    sa.Column('ai_model', sa.String(length=255), nullable=True),
    sa.Column('ai_max_tokens', sa.Integer(), nullable=True),
    sa.Column('ai_response_time', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True)
    )
    op.create_index('idx_sessions_session_id', 'sessions', ['session_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=255), primary_key=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('statement_index', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.CheckConstraint("sender IN ('user', 'system')", name='sender_type_check'),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    )
    op.create_index('idx_messages_session_id', 'messages', ['session_id'], unique=False)
    op.create_index('idx_messages_statement_index', 'messages', ['statement_index'], unique=False)
    op.create_index('idx_messages_session_statement_index', 'messages', ['session_id', 'statement_index'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), sa.Identity(), primary_key=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('to_statement_index', sa.Integer(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ),
    )
    op.create_index('idx_summaries_session_id', 'summaries', ['session_id'], unique=False)
    op.create_index('idx_summaries_to_statement_index', 'summaries', ['to_statement_index'], unique=False)
    op.create_index('idx_summaries_session_to_statement_index', 'summaries', ['session_id', 'to_statement_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_summaries_session_to_statement_index', table_name='summaries')
    op.drop_index('idx_summaries_to_statement_index', table_name='summaries')
    op.drop_index('idx_summaries_session_id', table_name='summaries')
    op.drop_table('summaries')
    op.drop_constraint('sender_type_check', 'messages', type_='check') # This still correctly drops the constraint
    op.drop_index('idx_messages_session_statement_index', table_name='messages')
    op.drop_index('idx_messages_statement_index', table_name='messages')
    op.drop_index('idx_messages_session_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_sessions_session_id', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
